language: groovy
before_install:
    - mvn com.savage7.maven.plugins:maven-external-dependency-plugin:resolve-external
    - mvn com.savage7.maven.plugins:maven-external-dependency-plugin:install-external
